/*===========================================================================*/
/* Module      = dr7f701035_irq.h                                            */
/* Version     = E9.10a                                                      */
/*               extracted from device file dr7f701035.dvf                   */
/*               generated by DeFiXRH850 0.6.2.0                             */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2013-2016 by Renesas Electronics Corporation                */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         R7F701035xAFP                                */
/*              IDE:            GHS Multi for V800  V6.xx or later           */
/*===========================================================================*/

#ifndef __R7F701035xAFP_IRQ_H
#define __R7F701035xAFP_IRQ_H

#define IRQ_TABLE_START                 0x00000200

#define RESET_ENABLE                    0x00000001

// #define SYSERR_ENABLE                   0x00000010

// #define FETRAPEX_ENABLE                 0x00000030

// #define EITRAP0_ENABLE                  0x00000040

// #define EITRAP1_ENABLE                  0x00000050

// #define RIEX_ENABLE                     0x00000060

// #define UCPOP_ENABLE                    0x00000080

// #define MIP_MDP_ENABLE                  0x00000090

// #define MAE_ENABLE                      0x000000C0

// #define FENMI_ENABLE                    0x000000E0

// #define FEINT_ENABLE                    0x000000F0

// #define EINTPRIO_0_ENABLE               0x00000100

// #define EINTPRIO_1_ENABLE               0x00000110

// #define EINTPRIO_2_ENABLE               0x00000120

// #define EINTPRIO_3_ENABLE               0x00000130

// #define EINTPRIO_4_ENABLE               0x00000140

// #define EINTPRIO_5_ENABLE               0x00000150

// #define EINTPRIO_6_ENABLE               0x00000160

// #define EINTPRIO_7_ENABLE               0x00000170

// #define EINTPRIO_8_ENABLE               0x00000180

// #define EINTPRIO_9_ENABLE               0x00000190

// #define EINTPRIO_10_ENABLE              0x000001A0

// #define EINTPRIO_11_ENABLE              0x000001B0

// #define EINTPRIO_12_ENABLE              0x000001C0

// #define EINTPRIO_13_ENABLE              0x000001D0

// #define EINTPRIO_14_ENABLE              0x000001E0

// #define EINTPRIO_15_ENABLE              0x000001F0

// #define INTTAUD0I0_ENABLE               (IRQ_TABLE_START + 0x00000000)

// #define INTCSIH2IC_1_ENABLE             (IRQ_TABLE_START + 0x00000000)

 
#ifndef INTTAUD0I0_ENABLE              
  #define INTTAUD0I0_ENABLE               0x00000000
#endif
#ifndef INTCSIH2IC_1_ENABLE            
  #define INTCSIH2IC_1_ENABLE             0x00000000
#endif
#if ( INTTAUD0I0_ENABLE + INTCSIH2IC_1_ENABLE) > (IRQ_TABLE_START + 0x00000000)
 #error Too many exception causes defined!
#endif

// #define INTCSIH3IC_1_ENABLE             (IRQ_TABLE_START + 0x00000004)

// #define INTTAUD0I2_ENABLE               (IRQ_TABLE_START + 0x00000004)

 
#ifndef INTCSIH3IC_1_ENABLE            
  #define INTCSIH3IC_1_ENABLE             0x00000000
#endif
#ifndef INTTAUD0I2_ENABLE              
  #define INTTAUD0I2_ENABLE               0x00000000
#endif
#if ( INTCSIH3IC_1_ENABLE + INTTAUD0I2_ENABLE) > (IRQ_TABLE_START + 0x00000004)
 #error Too many exception causes defined!
#endif

// #define INTTAUD0I4_ENABLE               (IRQ_TABLE_START + 0x00000008)

// #define INTTAUD0I6_ENABLE               (IRQ_TABLE_START + 0x0000000C)

// #define INTTAUD0I8_ENABLE               (IRQ_TABLE_START + 0x00000010)

// #define INTCSIH3IR_1_ENABLE             (IRQ_TABLE_START + 0x00000014)

// #define INTTAUD0I10_ENABLE              (IRQ_TABLE_START + 0x00000014)

 
#ifndef INTCSIH3IR_1_ENABLE            
  #define INTCSIH3IR_1_ENABLE             0x00000000
#endif
#ifndef INTTAUD0I10_ENABLE             
  #define INTTAUD0I10_ENABLE              0x00000000
#endif
#if ( INTCSIH3IR_1_ENABLE + INTTAUD0I10_ENABLE) > (IRQ_TABLE_START + 0x00000014)
 #error Too many exception causes defined!
#endif

// #define INTTAUD0I12_ENABLE              (IRQ_TABLE_START + 0x00000018)

// #define INTCSIH3IRE_1_ENABLE            (IRQ_TABLE_START + 0x00000018)

 
#ifndef INTTAUD0I12_ENABLE             
  #define INTTAUD0I12_ENABLE              0x00000000
#endif
#ifndef INTCSIH3IRE_1_ENABLE           
  #define INTCSIH3IRE_1_ENABLE            0x00000000
#endif
#if ( INTTAUD0I12_ENABLE + INTCSIH3IRE_1_ENABLE) > (IRQ_TABLE_START + 0x00000018)
 #error Too many exception causes defined!
#endif

// #define INTCSIH3IJC_1_ENABLE            (IRQ_TABLE_START + 0x0000001C)

// #define INTTAUD0I14_ENABLE              (IRQ_TABLE_START + 0x0000001C)

 
#ifndef INTCSIH3IJC_1_ENABLE           
  #define INTCSIH3IJC_1_ENABLE            0x00000000
#endif
#ifndef INTTAUD0I14_ENABLE             
  #define INTTAUD0I14_ENABLE              0x00000000
#endif
#if ( INTCSIH3IJC_1_ENABLE + INTTAUD0I14_ENABLE) > (IRQ_TABLE_START + 0x0000001C)
 #error Too many exception causes defined!
#endif

// #define INTTAPA0IPEK0_ENABLE            (IRQ_TABLE_START + 0x00000020)

// #define INTCSIH1IC_1_ENABLE             (IRQ_TABLE_START + 0x00000020)

 
#ifndef INTTAPA0IPEK0_ENABLE           
  #define INTTAPA0IPEK0_ENABLE            0x00000000
#endif
#ifndef INTCSIH1IC_1_ENABLE            
  #define INTCSIH1IC_1_ENABLE             0x00000000
#endif
#if ( INTTAPA0IPEK0_ENABLE + INTCSIH1IC_1_ENABLE) > (IRQ_TABLE_START + 0x00000020)
 #error Too many exception causes defined!
#endif

// #define INTCSIH1IR_1_ENABLE             (IRQ_TABLE_START + 0x00000024)

// #define INTTAPA0IVLY0_ENABLE            (IRQ_TABLE_START + 0x00000024)

 
#ifndef INTCSIH1IR_1_ENABLE            
  #define INTCSIH1IR_1_ENABLE             0x00000000
#endif
#ifndef INTTAPA0IVLY0_ENABLE           
  #define INTTAPA0IVLY0_ENABLE            0x00000000
#endif
#if ( INTCSIH1IR_1_ENABLE + INTTAPA0IVLY0_ENABLE) > (IRQ_TABLE_START + 0x00000024)
 #error Too many exception causes defined!
#endif

// #define INTADCA0I0_ENABLE               (IRQ_TABLE_START + 0x00000028)

// #define INTADCA0I1_ENABLE               (IRQ_TABLE_START + 0x0000002C)

// #define INTADCA0I2_ENABLE               (IRQ_TABLE_START + 0x00000030)

// #define INTDCUTDI_ENABLE                (IRQ_TABLE_START + 0x00000034)

// #define INTRCANGERR_ENABLE              (IRQ_TABLE_START + 0x00000038)

// #define INTRCANGRECC_ENABLE             (IRQ_TABLE_START + 0x0000003C)

// #define INTRCAN0ERR_ENABLE              (IRQ_TABLE_START + 0x00000040)

// #define INTRCAN0REC_ENABLE              (IRQ_TABLE_START + 0x00000044)

// #define INTRCAN0TRX_ENABLE              (IRQ_TABLE_START + 0x00000048)

// #define INTCSIG0IC_ENABLE               (IRQ_TABLE_START + 0x0000004C)

// #define INTCSIH1IRE_1_ENABLE            (IRQ_TABLE_START + 0x0000004C)

 
#ifndef INTCSIG0IC_ENABLE              
  #define INTCSIG0IC_ENABLE               0x00000000
#endif
#ifndef INTCSIH1IRE_1_ENABLE           
  #define INTCSIH1IRE_1_ENABLE            0x00000000
#endif
#if ( INTCSIG0IC_ENABLE + INTCSIH1IRE_1_ENABLE) > (IRQ_TABLE_START + 0x0000004C)
 #error Too many exception causes defined!
#endif

// #define INTCSIH1IJC_1_ENABLE            (IRQ_TABLE_START + 0x00000050)

// #define INTCSIG0IR_ENABLE               (IRQ_TABLE_START + 0x00000050)

 
#ifndef INTCSIH1IJC_1_ENABLE           
  #define INTCSIH1IJC_1_ENABLE            0x00000000
#endif
#ifndef INTCSIG0IR_ENABLE              
  #define INTCSIG0IR_ENABLE               0x00000000
#endif
#if ( INTCSIH1IJC_1_ENABLE + INTCSIG0IR_ENABLE) > (IRQ_TABLE_START + 0x00000050)
 #error Too many exception causes defined!
#endif

// #define INTCSIH0IC_ENABLE               (IRQ_TABLE_START + 0x00000054)

// #define INTCSIH0IR_ENABLE               (IRQ_TABLE_START + 0x00000058)

// #define INTCSIH0IRE_ENABLE              (IRQ_TABLE_START + 0x0000005C)

// #define INTCSIH0IJC_ENABLE              (IRQ_TABLE_START + 0x00000060)

// #define INTRLIN30_ENABLE                (IRQ_TABLE_START + 0x00000064)

// #define INTRLIN30UR0_ENABLE             (IRQ_TABLE_START + 0x00000068)

// #define INTRLIN30UR1_ENABLE             (IRQ_TABLE_START + 0x0000006C)

// #define INTRLIN30UR2_ENABLE             (IRQ_TABLE_START + 0x00000070)

// #define INTP0_ENABLE                    (IRQ_TABLE_START + 0x00000074)

// #define INTCSIH2IR_1_ENABLE             (IRQ_TABLE_START + 0x00000074)

 
#ifndef INTP0_ENABLE                   
  #define INTP0_ENABLE                    0x00000000
#endif
#ifndef INTCSIH2IR_1_ENABLE            
  #define INTCSIH2IR_1_ENABLE             0x00000000
#endif
#if ( INTP0_ENABLE + INTCSIH2IR_1_ENABLE) > (IRQ_TABLE_START + 0x00000074)
 #error Too many exception causes defined!
#endif

// #define INTP1_ENABLE                    (IRQ_TABLE_START + 0x00000078)

// #define INTCSIH2IRE_1_ENABLE            (IRQ_TABLE_START + 0x00000078)

 
#ifndef INTP1_ENABLE                   
  #define INTP1_ENABLE                    0x00000000
#endif
#ifndef INTCSIH2IRE_1_ENABLE           
  #define INTCSIH2IRE_1_ENABLE            0x00000000
#endif
#if ( INTP1_ENABLE + INTCSIH2IRE_1_ENABLE) > (IRQ_TABLE_START + 0x00000078)
 #error Too many exception causes defined!
#endif

// #define INTP2_ENABLE                    (IRQ_TABLE_START + 0x0000007C)

// #define INTCSIH2IJC_1_ENABLE            (IRQ_TABLE_START + 0x0000007C)

 
#ifndef INTP2_ENABLE                   
  #define INTP2_ENABLE                    0x00000000
#endif
#ifndef INTCSIH2IJC_1_ENABLE           
  #define INTCSIH2IJC_1_ENABLE            0x00000000
#endif
#if ( INTP2_ENABLE + INTCSIH2IJC_1_ENABLE) > (IRQ_TABLE_START + 0x0000007C)
 #error Too many exception causes defined!
#endif

// #define INTWDTA0_ENABLE                 (IRQ_TABLE_START + 0x00000080)

// #define INTWDTA1_ENABLE                 (IRQ_TABLE_START + 0x00000084)

// #define INTP3_ENABLE                    (IRQ_TABLE_START + 0x00000088)

// #define INTP4_ENABLE                    (IRQ_TABLE_START + 0x0000008C)

// #define INTP5_ENABLE                    (IRQ_TABLE_START + 0x00000090)

// #define INTP10_ENABLE                   (IRQ_TABLE_START + 0x00000094)

// #define INTP11_ENABLE                   (IRQ_TABLE_START + 0x00000098)

// #define INTTAUD0I1_ENABLE               (IRQ_TABLE_START + 0x0000009C)

// #define INTTAUD0I3_ENABLE               (IRQ_TABLE_START + 0x000000A0)

// #define INTTAUD0I5_ENABLE               (IRQ_TABLE_START + 0x000000A4)

// #define INTTAUD0I7_ENABLE               (IRQ_TABLE_START + 0x000000A8)

// #define INTTAUD0I9_ENABLE               (IRQ_TABLE_START + 0x000000AC)

// #define INTTAUD0I11_ENABLE              (IRQ_TABLE_START + 0x000000B0)

// #define INTTAUD0I13_ENABLE              (IRQ_TABLE_START + 0x000000B4)

// #define INTTAUD0I15_ENABLE              (IRQ_TABLE_START + 0x000000B8)

// #define INTADCA0ERR_ENABLE              (IRQ_TABLE_START + 0x000000BC)

// #define INTCSIG0IRE_ENABLE              (IRQ_TABLE_START + 0x000000C4)

// #define INTRLIN20_ENABLE                (IRQ_TABLE_START + 0x000000C8)

// #define INTRLIN21_ENABLE                (IRQ_TABLE_START + 0x000000CC)

// #define INTDMA0_ENABLE                  (IRQ_TABLE_START + 0x000000D0)

// #define INTDMA1_ENABLE                  (IRQ_TABLE_START + 0x000000D4)

// #define INTDMA2_ENABLE                  (IRQ_TABLE_START + 0x000000D8)

// #define INTDMA3_ENABLE                  (IRQ_TABLE_START + 0x000000DC)

// #define INTDMA4_ENABLE                  (IRQ_TABLE_START + 0x000000E0)

// #define INTDMA5_ENABLE                  (IRQ_TABLE_START + 0x000000E4)

// #define INTDMA6_ENABLE                  (IRQ_TABLE_START + 0x000000E8)

// #define INTDMA7_ENABLE                  (IRQ_TABLE_START + 0x000000EC)

// #define INTDMA8_ENABLE                  (IRQ_TABLE_START + 0x000000F0)

// #define INTDMA9_ENABLE                  (IRQ_TABLE_START + 0x000000F4)

// #define INTDMA10_ENABLE                 (IRQ_TABLE_START + 0x000000F8)

// #define INTDMA11_ENABLE                 (IRQ_TABLE_START + 0x000000FC)

// #define INTDMA12_ENABLE                 (IRQ_TABLE_START + 0x00000100)

// #define INTDMA13_ENABLE                 (IRQ_TABLE_START + 0x00000104)

// #define INTDMA14_ENABLE                 (IRQ_TABLE_START + 0x00000108)

// #define INTDMA15_ENABLE                 (IRQ_TABLE_START + 0x0000010C)

// #define INTRIIC0TI_ENABLE               (IRQ_TABLE_START + 0x00000110)

// #define INTRIIC0TEI_ENABLE              (IRQ_TABLE_START + 0x00000114)

// #define INTRIIC0RI_ENABLE               (IRQ_TABLE_START + 0x00000118)

// #define INTRIIC0EE_ENABLE               (IRQ_TABLE_START + 0x0000011C)

// #define INTTAUJ0I0_ENABLE               (IRQ_TABLE_START + 0x00000120)

// #define INTTAUJ0I1_ENABLE               (IRQ_TABLE_START + 0x00000124)

// #define INTTAUJ0I2_ENABLE               (IRQ_TABLE_START + 0x00000128)

// #define INTTAUJ0I3_ENABLE               (IRQ_TABLE_START + 0x0000012C)

// #define INTOSTM0_ENABLE                 (IRQ_TABLE_START + 0x00000130)

// #define INTENCA0IOV_ENABLE              (IRQ_TABLE_START + 0x00000134)

// #define INTPWGA4_ENABLE                 (IRQ_TABLE_START + 0x00000134)

 
#ifndef INTENCA0IOV_ENABLE             
  #define INTENCA0IOV_ENABLE              0x00000000
#endif
#ifndef INTPWGA4_ENABLE                
  #define INTPWGA4_ENABLE                 0x00000000
#endif
#if ( INTENCA0IOV_ENABLE + INTPWGA4_ENABLE) > (IRQ_TABLE_START + 0x00000134)
 #error Too many exception causes defined!
#endif

// #define INTPWGA5_ENABLE                 (IRQ_TABLE_START + 0x00000138)

// #define INTENCA0IUD_ENABLE              (IRQ_TABLE_START + 0x00000138)

 
#ifndef INTPWGA5_ENABLE                
  #define INTPWGA5_ENABLE                 0x00000000
#endif
#ifndef INTENCA0IUD_ENABLE             
  #define INTENCA0IUD_ENABLE              0x00000000
#endif
#if ( INTPWGA5_ENABLE + INTENCA0IUD_ENABLE) > (IRQ_TABLE_START + 0x00000138)
 #error Too many exception causes defined!
#endif

// #define INTENCA0I0_ENABLE               (IRQ_TABLE_START + 0x0000013C)

// #define INTPWGA6_ENABLE                 (IRQ_TABLE_START + 0x0000013C)

 
#ifndef INTENCA0I0_ENABLE              
  #define INTENCA0I0_ENABLE               0x00000000
#endif
#ifndef INTPWGA6_ENABLE                
  #define INTPWGA6_ENABLE                 0x00000000
#endif
#if ( INTENCA0I0_ENABLE + INTPWGA6_ENABLE) > (IRQ_TABLE_START + 0x0000013C)
 #error Too many exception causes defined!
#endif

// #define INTENCA0I1_ENABLE               (IRQ_TABLE_START + 0x00000140)

// #define INTPWGA7_ENABLE                 (IRQ_TABLE_START + 0x00000140)

 
#ifndef INTENCA0I1_ENABLE              
  #define INTENCA0I1_ENABLE               0x00000000
#endif
#ifndef INTPWGA7_ENABLE                
  #define INTPWGA7_ENABLE                 0x00000000
#endif
#if ( INTENCA0I1_ENABLE + INTPWGA7_ENABLE) > (IRQ_TABLE_START + 0x00000140)
 #error Too many exception causes defined!
#endif

// #define INTENCA0IEC_ENABLE              (IRQ_TABLE_START + 0x00000144)

// #define INTKR0_ENABLE                   (IRQ_TABLE_START + 0x00000148)

// #define INTQFULL_ENABLE                 (IRQ_TABLE_START + 0x0000014C)

// #define INTPWGA0_ENABLE                 (IRQ_TABLE_START + 0x00000150)

// #define INTPWGA1_ENABLE                 (IRQ_TABLE_START + 0x00000154)

// #define INTPWGA2_ENABLE                 (IRQ_TABLE_START + 0x00000158)

// #define INTPWGA3_ENABLE                 (IRQ_TABLE_START + 0x0000015C)

// #define INTPWGA8_ENABLE                 (IRQ_TABLE_START + 0x00000160)

// #define INTPWGA9_ENABLE                 (IRQ_TABLE_START + 0x00000164)

// #define INTPWGA10_ENABLE                (IRQ_TABLE_START + 0x00000168)

// #define INTPWGA11_ENABLE                (IRQ_TABLE_START + 0x0000016C)

// #define INTPWGA12_ENABLE                (IRQ_TABLE_START + 0x00000170)

// #define INTPWGA13_ENABLE                (IRQ_TABLE_START + 0x00000174)

// #define INTPWGA14_ENABLE                (IRQ_TABLE_START + 0x00000178)

// #define INTPWGA15_ENABLE                (IRQ_TABLE_START + 0x0000017C)

// #define INTICUSTWRDY_ENABLE             (IRQ_TABLE_START + 0x00000180)

// #define INTICUSTRRDY_ENABLE             (IRQ_TABLE_START + 0x00000184)

// #define INTFLERR_ENABLE                 (IRQ_TABLE_START + 0x00000198)

// #define INTFLENDNM_ENABLE               (IRQ_TABLE_START + 0x0000019C)

// #define INTCWEND_ENABLE                 (IRQ_TABLE_START + 0x000001A0)

// #define INTRCAN1ERR_ENABLE              (IRQ_TABLE_START + 0x000001A4)

// #define INTRCAN1REC_ENABLE              (IRQ_TABLE_START + 0x000001A8)

// #define INTRCAN1TRX_ENABLE              (IRQ_TABLE_START + 0x000001AC)

// #define INTCSIH1IC_ENABLE               (IRQ_TABLE_START + 0x000001B0)

// #define INTTAPA0IPEK0_2_ENABLE          (IRQ_TABLE_START + 0x000001B0)

 
#ifndef INTCSIH1IC_ENABLE              
  #define INTCSIH1IC_ENABLE               0x00000000
#endif
#ifndef INTTAPA0IPEK0_2_ENABLE         
  #define INTTAPA0IPEK0_2_ENABLE          0x00000000
#endif
#if ( INTCSIH1IC_ENABLE + INTTAPA0IPEK0_2_ENABLE) > (IRQ_TABLE_START + 0x000001B0)
 #error Too many exception causes defined!
#endif

// #define INTTAPA0IVLY0_2_ENABLE          (IRQ_TABLE_START + 0x000001B4)

// #define INTCSIH1IR_ENABLE               (IRQ_TABLE_START + 0x000001B4)

 
#ifndef INTTAPA0IVLY0_2_ENABLE         
  #define INTTAPA0IVLY0_2_ENABLE          0x00000000
#endif
#ifndef INTCSIH1IR_ENABLE              
  #define INTCSIH1IR_ENABLE               0x00000000
#endif
#if ( INTTAPA0IVLY0_2_ENABLE + INTCSIH1IR_ENABLE) > (IRQ_TABLE_START + 0x000001B4)
 #error Too many exception causes defined!
#endif

// #define INTCSIG0IC_2_ENABLE             (IRQ_TABLE_START + 0x000001B8)

// #define INTCSIH1IRE_ENABLE              (IRQ_TABLE_START + 0x000001B8)

 
#ifndef INTCSIG0IC_2_ENABLE            
  #define INTCSIG0IC_2_ENABLE             0x00000000
#endif
#ifndef INTCSIH1IRE_ENABLE             
  #define INTCSIH1IRE_ENABLE              0x00000000
#endif
#if ( INTCSIG0IC_2_ENABLE + INTCSIH1IRE_ENABLE) > (IRQ_TABLE_START + 0x000001B8)
 #error Too many exception causes defined!
#endif

// #define INTCSIH1IJC_ENABLE              (IRQ_TABLE_START + 0x000001BC)

// #define INTCSIG0IR_2_ENABLE             (IRQ_TABLE_START + 0x000001BC)

 
#ifndef INTCSIH1IJC_ENABLE             
  #define INTCSIH1IJC_ENABLE              0x00000000
#endif
#ifndef INTCSIG0IR_2_ENABLE            
  #define INTCSIG0IR_2_ENABLE             0x00000000
#endif
#if ( INTCSIH1IJC_ENABLE + INTCSIG0IR_2_ENABLE) > (IRQ_TABLE_START + 0x000001BC)
 #error Too many exception causes defined!
#endif

// #define INTRLIN31_ENABLE                (IRQ_TABLE_START + 0x000001C0)

// #define INTRLIN31UR0_ENABLE             (IRQ_TABLE_START + 0x000001C4)

// #define INTRLIN31UR1_ENABLE             (IRQ_TABLE_START + 0x000001C8)

// #define INTRLIN31UR2_ENABLE             (IRQ_TABLE_START + 0x000001CC)

// #define INTPWGA20_ENABLE                (IRQ_TABLE_START + 0x000001D0)

// #define INTPWGA21_ENABLE                (IRQ_TABLE_START + 0x000001D4)

// #define INTPWGA22_ENABLE                (IRQ_TABLE_START + 0x000001D8)

// #define INTPWGA23_ENABLE                (IRQ_TABLE_START + 0x000001DC)

// #define INTP6_ENABLE                    (IRQ_TABLE_START + 0x000001E0)

// #define INTP7_ENABLE                    (IRQ_TABLE_START + 0x000001E4)

// #define INTP8_ENABLE                    (IRQ_TABLE_START + 0x000001E8)

// #define INTP12_ENABLE                   (IRQ_TABLE_START + 0x000001EC)

// #define INTTAUD0I0_2_ENABLE             (IRQ_TABLE_START + 0x000001F0)

// #define INTCSIH2IC_ENABLE               (IRQ_TABLE_START + 0x000001F0)

 
#ifndef INTTAUD0I0_2_ENABLE            
  #define INTTAUD0I0_2_ENABLE             0x00000000
#endif
#ifndef INTCSIH2IC_ENABLE              
  #define INTCSIH2IC_ENABLE               0x00000000
#endif
#if ( INTTAUD0I0_2_ENABLE + INTCSIH2IC_ENABLE) > (IRQ_TABLE_START + 0x000001F0)
 #error Too many exception causes defined!
#endif

// #define INTP0_2_ENABLE                  (IRQ_TABLE_START + 0x000001F4)

// #define INTCSIH2IR_ENABLE               (IRQ_TABLE_START + 0x000001F4)

 
#ifndef INTP0_2_ENABLE                 
  #define INTP0_2_ENABLE                  0x00000000
#endif
#ifndef INTCSIH2IR_ENABLE              
  #define INTCSIH2IR_ENABLE               0x00000000
#endif
#if ( INTP0_2_ENABLE + INTCSIH2IR_ENABLE) > (IRQ_TABLE_START + 0x000001F4)
 #error Too many exception causes defined!
#endif

// #define INTP1_2_ENABLE                  (IRQ_TABLE_START + 0x000001F8)

// #define INTCSIH2IRE_ENABLE              (IRQ_TABLE_START + 0x000001F8)

 
#ifndef INTP1_2_ENABLE                 
  #define INTP1_2_ENABLE                  0x00000000
#endif
#ifndef INTCSIH2IRE_ENABLE             
  #define INTCSIH2IRE_ENABLE              0x00000000
#endif
#if ( INTP1_2_ENABLE + INTCSIH2IRE_ENABLE) > (IRQ_TABLE_START + 0x000001F8)
 #error Too many exception causes defined!
#endif

// #define INTCSIH2IJC_ENABLE              (IRQ_TABLE_START + 0x000001FC)

// #define INTP2_2_ENABLE                  (IRQ_TABLE_START + 0x000001FC)

 
#ifndef INTCSIH2IJC_ENABLE             
  #define INTCSIH2IJC_ENABLE              0x00000000
#endif
#ifndef INTP2_2_ENABLE                 
  #define INTP2_2_ENABLE                  0x00000000
#endif
#if ( INTCSIH2IJC_ENABLE + INTP2_2_ENABLE) > (IRQ_TABLE_START + 0x000001FC)
 #error Too many exception causes defined!
#endif

// #define INTTAUB0I0_ENABLE               (IRQ_TABLE_START + 0x00000218)

// #define INTTAUB0I1_ENABLE               (IRQ_TABLE_START + 0x0000021C)

// #define INTTAUB0I2_ENABLE               (IRQ_TABLE_START + 0x00000220)

// #define INTPWGA16_ENABLE                (IRQ_TABLE_START + 0x00000224)

// #define INTTAUB0I3_ENABLE               (IRQ_TABLE_START + 0x00000224)

 
#ifndef INTPWGA16_ENABLE               
  #define INTPWGA16_ENABLE                0x00000000
#endif
#ifndef INTTAUB0I3_ENABLE              
  #define INTTAUB0I3_ENABLE               0x00000000
#endif
#if ( INTPWGA16_ENABLE + INTTAUB0I3_ENABLE) > (IRQ_TABLE_START + 0x00000224)
 #error Too many exception causes defined!
#endif

// #define INTTAUB0I4_ENABLE               (IRQ_TABLE_START + 0x00000228)

// #define INTTAUB0I5_ENABLE               (IRQ_TABLE_START + 0x0000022C)

// #define INTPWGA17_ENABLE                (IRQ_TABLE_START + 0x0000022C)

 
#ifndef INTTAUB0I5_ENABLE              
  #define INTTAUB0I5_ENABLE               0x00000000
#endif
#ifndef INTPWGA17_ENABLE               
  #define INTPWGA17_ENABLE                0x00000000
#endif
#if ( INTTAUB0I5_ENABLE + INTPWGA17_ENABLE) > (IRQ_TABLE_START + 0x0000022C)
 #error Too many exception causes defined!
#endif

// #define INTTAUB0I6_ENABLE               (IRQ_TABLE_START + 0x00000230)

// #define INTPWGA18_ENABLE                (IRQ_TABLE_START + 0x00000234)

// #define INTTAUB0I7_ENABLE               (IRQ_TABLE_START + 0x00000234)

 
#ifndef INTPWGA18_ENABLE               
  #define INTPWGA18_ENABLE                0x00000000
#endif
#ifndef INTTAUB0I7_ENABLE              
  #define INTTAUB0I7_ENABLE               0x00000000
#endif
#if ( INTPWGA18_ENABLE + INTTAUB0I7_ENABLE) > (IRQ_TABLE_START + 0x00000234)
 #error Too many exception causes defined!
#endif

// #define INTTAUB0I8_ENABLE               (IRQ_TABLE_START + 0x00000238)

// #define INTPWGA19_ENABLE                (IRQ_TABLE_START + 0x0000023C)

// #define INTTAUB0I9_ENABLE               (IRQ_TABLE_START + 0x0000023C)

 
#ifndef INTPWGA19_ENABLE               
  #define INTPWGA19_ENABLE                0x00000000
#endif
#ifndef INTTAUB0I9_ENABLE              
  #define INTTAUB0I9_ENABLE               0x00000000
#endif
#if ( INTPWGA19_ENABLE + INTTAUB0I9_ENABLE) > (IRQ_TABLE_START + 0x0000023C)
 #error Too many exception causes defined!
#endif

// #define INTTAUB0I10_ENABLE              (IRQ_TABLE_START + 0x00000240)

// #define INTTAUB0I11_ENABLE              (IRQ_TABLE_START + 0x00000244)

// #define INTPWGA26_ENABLE                (IRQ_TABLE_START + 0x00000244)

 
#ifndef INTTAUB0I11_ENABLE             
  #define INTTAUB0I11_ENABLE              0x00000000
#endif
#ifndef INTPWGA26_ENABLE               
  #define INTPWGA26_ENABLE                0x00000000
#endif
#if ( INTTAUB0I11_ENABLE + INTPWGA26_ENABLE) > (IRQ_TABLE_START + 0x00000244)
 #error Too many exception causes defined!
#endif

// #define INTTAUB0I12_ENABLE              (IRQ_TABLE_START + 0x00000248)

// #define INTTAUB0I13_ENABLE              (IRQ_TABLE_START + 0x0000024C)

// #define INTPWGA30_ENABLE                (IRQ_TABLE_START + 0x0000024C)

 
#ifndef INTTAUB0I13_ENABLE             
  #define INTTAUB0I13_ENABLE              0x00000000
#endif
#ifndef INTPWGA30_ENABLE               
  #define INTPWGA30_ENABLE                0x00000000
#endif
#if ( INTTAUB0I13_ENABLE + INTPWGA30_ENABLE) > (IRQ_TABLE_START + 0x0000024C)
 #error Too many exception causes defined!
#endif

// #define INTTAUB0I14_ENABLE              (IRQ_TABLE_START + 0x00000250)

// #define INTTAUB0I15_ENABLE              (IRQ_TABLE_START + 0x00000254)

// #define INTPWGA31_ENABLE                (IRQ_TABLE_START + 0x00000254)

 
#ifndef INTTAUB0I15_ENABLE             
  #define INTTAUB0I15_ENABLE              0x00000000
#endif
#ifndef INTPWGA31_ENABLE               
  #define INTPWGA31_ENABLE                0x00000000
#endif
#if ( INTTAUB0I15_ENABLE + INTPWGA31_ENABLE) > (IRQ_TABLE_START + 0x00000254)
 #error Too many exception causes defined!
#endif

// #define INTTAUD0I2_2_ENABLE             (IRQ_TABLE_START + 0x00000258)

// #define INTCSIH3IC_ENABLE               (IRQ_TABLE_START + 0x00000258)

 
#ifndef INTTAUD0I2_2_ENABLE            
  #define INTTAUD0I2_2_ENABLE             0x00000000
#endif
#ifndef INTCSIH3IC_ENABLE              
  #define INTCSIH3IC_ENABLE               0x00000000
#endif
#if ( INTTAUD0I2_2_ENABLE + INTCSIH3IC_ENABLE) > (IRQ_TABLE_START + 0x00000258)
 #error Too many exception causes defined!
#endif

// #define INTCSIH3IR_ENABLE               (IRQ_TABLE_START + 0x0000025C)

// #define INTTAUD0I10_2_ENABLE            (IRQ_TABLE_START + 0x0000025C)

 
#ifndef INTCSIH3IR_ENABLE              
  #define INTCSIH3IR_ENABLE               0x00000000
#endif
#ifndef INTTAUD0I10_2_ENABLE           
  #define INTTAUD0I10_2_ENABLE            0x00000000
#endif
#if ( INTCSIH3IR_ENABLE + INTTAUD0I10_2_ENABLE) > (IRQ_TABLE_START + 0x0000025C)
 #error Too many exception causes defined!
#endif

// #define INTCSIH3IRE_ENABLE              (IRQ_TABLE_START + 0x00000260)

// #define INTTAUD0I12_2_ENABLE            (IRQ_TABLE_START + 0x00000260)

 
#ifndef INTCSIH3IRE_ENABLE             
  #define INTCSIH3IRE_ENABLE              0x00000000
#endif
#ifndef INTTAUD0I12_2_ENABLE           
  #define INTTAUD0I12_2_ENABLE            0x00000000
#endif
#if ( INTCSIH3IRE_ENABLE + INTTAUD0I12_2_ENABLE) > (IRQ_TABLE_START + 0x00000260)
 #error Too many exception causes defined!
#endif

// #define INTTAUD0I14_2_ENABLE            (IRQ_TABLE_START + 0x00000264)

// #define INTCSIH3IJC_ENABLE              (IRQ_TABLE_START + 0x00000264)

 
#ifndef INTTAUD0I14_2_ENABLE           
  #define INTTAUD0I14_2_ENABLE            0x00000000
#endif
#ifndef INTCSIH3IJC_ENABLE             
  #define INTCSIH3IJC_ENABLE              0x00000000
#endif
#if ( INTTAUD0I14_2_ENABLE + INTCSIH3IJC_ENABLE) > (IRQ_TABLE_START + 0x00000264)
 #error Too many exception causes defined!
#endif

// #define INTRLIN22_ENABLE                (IRQ_TABLE_START + 0x00000268)

// #define INTRLIN23_ENABLE                (IRQ_TABLE_START + 0x0000026C)

// #define INTRLIN32_ENABLE                (IRQ_TABLE_START + 0x00000270)

// #define INTRLIN32UR0_ENABLE             (IRQ_TABLE_START + 0x00000274)

// #define INTRLIN32UR1_ENABLE             (IRQ_TABLE_START + 0x00000278)

// #define INTRLIN32UR2_ENABLE             (IRQ_TABLE_START + 0x0000027C)

// #define INTTAUJ1I0_ENABLE               (IRQ_TABLE_START + 0x00000280)

// #define INTTAUJ1I1_ENABLE               (IRQ_TABLE_START + 0x00000284)

// #define INTTAUJ1I2_ENABLE               (IRQ_TABLE_START + 0x00000288)

// #define INTTAUJ1I3_ENABLE               (IRQ_TABLE_START + 0x0000028C)

// #define INTPWGA24_ENABLE                (IRQ_TABLE_START + 0x000002C0)

// #define INTPWGA25_ENABLE                (IRQ_TABLE_START + 0x000002C4)

// #define INTPWGA27_ENABLE                (IRQ_TABLE_START + 0x000002C8)

// #define INTPWGA28_ENABLE                (IRQ_TABLE_START + 0x000002CC)

// #define INTPWGA29_ENABLE                (IRQ_TABLE_START + 0x000002D0)

// #define INTPWGA32_ENABLE                (IRQ_TABLE_START + 0x000002D4)

// #define INTPWGA33_ENABLE                (IRQ_TABLE_START + 0x000002D8)

// #define INTPWGA34_ENABLE                (IRQ_TABLE_START + 0x000002DC)

// #define INTPWGA35_ENABLE                (IRQ_TABLE_START + 0x000002E0)

// #define INTPWGA36_ENABLE                (IRQ_TABLE_START + 0x000002E4)

// #define INTPWGA37_ENABLE                (IRQ_TABLE_START + 0x000002E8)

// #define INTPWGA38_ENABLE                (IRQ_TABLE_START + 0x000002EC)

// #define INTPWGA39_ENABLE                (IRQ_TABLE_START + 0x000002F0)

// #define INTPWGA40_ENABLE                (IRQ_TABLE_START + 0x000002F4)

// #define INTPWGA41_ENABLE                (IRQ_TABLE_START + 0x000002F8)

// #define INTPWGA42_ENABLE                (IRQ_TABLE_START + 0x000002FC)

// #define INTPWGA43_ENABLE                (IRQ_TABLE_START + 0x00000300)

// #define INTPWGA44_ENABLE                (IRQ_TABLE_START + 0x00000304)

// #define INTPWGA45_ENABLE                (IRQ_TABLE_START + 0x00000308)

// #define INTPWGA46_ENABLE                (IRQ_TABLE_START + 0x0000030C)

// #define INTPWGA47_ENABLE                (IRQ_TABLE_START + 0x00000310)

// #define INTP9_ENABLE                    (IRQ_TABLE_START + 0x00000314)

// #define INTP13_ENABLE                   (IRQ_TABLE_START + 0x00000318)

// #define INTP14_ENABLE                   (IRQ_TABLE_START + 0x0000031C)

// #define INTP15_ENABLE                   (IRQ_TABLE_START + 0x00000320)

// #define INTRTCA01S_ENABLE               (IRQ_TABLE_START + 0x00000324)

// #define INTRTCA0AL_ENABLE               (IRQ_TABLE_START + 0x00000328)

// #define INTRTCA0R_ENABLE                (IRQ_TABLE_START + 0x0000032C)

// #define INTADCA1ERR_ENABLE              (IRQ_TABLE_START + 0x00000330)

// #define INTADCA1I0_ENABLE               (IRQ_TABLE_START + 0x00000334)

// #define INTADCA1I1_ENABLE               (IRQ_TABLE_START + 0x00000338)

// #define INTADCA1I2_ENABLE               (IRQ_TABLE_START + 0x0000033C)

// #define INTRCAN2ERR_ENABLE              (IRQ_TABLE_START + 0x00000344)

// #define INTRCAN2REC_ENABLE              (IRQ_TABLE_START + 0x00000348)

// #define INTRCAN2TRX_ENABLE              (IRQ_TABLE_START + 0x0000034C)

// #define INTRCAN3ERR_ENABLE              (IRQ_TABLE_START + 0x00000350)

// #define INTRCAN3REC_ENABLE              (IRQ_TABLE_START + 0x00000354)

// #define INTRCAN3TRX_ENABLE              (IRQ_TABLE_START + 0x00000358)

// #define INTCSIG1IC_ENABLE               (IRQ_TABLE_START + 0x0000035C)

// #define INTCSIG1IR_ENABLE               (IRQ_TABLE_START + 0x00000360)

// #define INTCSIG1IRE_ENABLE              (IRQ_TABLE_START + 0x00000364)

// #define INTRLIN24_ENABLE                (IRQ_TABLE_START + 0x00000368)

// #define INTRLIN25_ENABLE                (IRQ_TABLE_START + 0x0000036C)

// #define INTRLIN33_ENABLE                (IRQ_TABLE_START + 0x00000370)

// #define INTRLIN33UR0_ENABLE             (IRQ_TABLE_START + 0x00000374)

// #define INTRLIN33UR1_ENABLE             (IRQ_TABLE_START + 0x00000378)

// #define INTRLIN33UR2_ENABLE             (IRQ_TABLE_START + 0x0000037C)

// #define INTRLIN34_ENABLE                (IRQ_TABLE_START + 0x00000380)

// #define INTRLIN34UR0_ENABLE             (IRQ_TABLE_START + 0x00000384)

// #define INTRLIN34UR1_ENABLE             (IRQ_TABLE_START + 0x00000388)

// #define INTRLIN34UR2_ENABLE             (IRQ_TABLE_START + 0x0000038C)

// #define INTRLIN35_ENABLE                (IRQ_TABLE_START + 0x00000390)

// #define INTRLIN35UR0_ENABLE             (IRQ_TABLE_START + 0x00000394)

// #define INTRLIN35UR1_ENABLE             (IRQ_TABLE_START + 0x00000398)

// #define INTRLIN35UR2_ENABLE             (IRQ_TABLE_START + 0x0000039C)

// #define INTPWGA48_ENABLE                (IRQ_TABLE_START + 0x000003A0)

// #define INTPWGA49_ENABLE                (IRQ_TABLE_START + 0x000003A4)

// #define INTPWGA50_ENABLE                (IRQ_TABLE_START + 0x000003A8)

// #define INTPWGA51_ENABLE                (IRQ_TABLE_START + 0x000003AC)

// #define INTPWGA52_ENABLE                (IRQ_TABLE_START + 0x000003B0)

// #define INTPWGA53_ENABLE                (IRQ_TABLE_START + 0x000003B4)

// #define INTPWGA54_ENABLE                (IRQ_TABLE_START + 0x000003B8)

// #define INTPWGA55_ENABLE                (IRQ_TABLE_START + 0x000003BC)

// #define INTPWGA56_ENABLE                (IRQ_TABLE_START + 0x000003C0)

// #define INTPWGA57_ENABLE                (IRQ_TABLE_START + 0x000003C4)

// #define INTPWGA58_ENABLE                (IRQ_TABLE_START + 0x000003C8)

// #define INTPWGA59_ENABLE                (IRQ_TABLE_START + 0x000003CC)

// #define INTPWGA60_ENABLE                (IRQ_TABLE_START + 0x000003D0)

// #define INTPWGA61_ENABLE                (IRQ_TABLE_START + 0x000003D4)

// #define INTPWGA62_ENABLE                (IRQ_TABLE_START + 0x000003D8)

// #define INTPWGA63_ENABLE                (IRQ_TABLE_START + 0x000003DC)

// #define INTTAUB1I0_ENABLE               (IRQ_TABLE_START + 0x000003E0)

// #define INTTAUB1I1_ENABLE               (IRQ_TABLE_START + 0x000003E4)

// #define INTTAUB1I2_ENABLE               (IRQ_TABLE_START + 0x000003E8)

// #define INTTAUB1I3_ENABLE               (IRQ_TABLE_START + 0x000003EC)

// #define INTTAUB1I4_ENABLE               (IRQ_TABLE_START + 0x000003F0)

// #define INTTAUB1I5_ENABLE               (IRQ_TABLE_START + 0x000003F4)

// #define INTTAUB1I6_ENABLE               (IRQ_TABLE_START + 0x000003F8)

// #define INTTAUB1I7_ENABLE               (IRQ_TABLE_START + 0x000003FC)

// #define INTTAUB1I8_ENABLE               (IRQ_TABLE_START + 0x00000400)

// #define INTTAUB1I9_ENABLE               (IRQ_TABLE_START + 0x00000404)

// #define INTTAUB1I10_ENABLE              (IRQ_TABLE_START + 0x00000408)

// #define INTTAUB1I11_ENABLE              (IRQ_TABLE_START + 0x0000040C)

// #define INTTAUB1I12_ENABLE              (IRQ_TABLE_START + 0x00000410)

// #define INTTAUB1I13_ENABLE              (IRQ_TABLE_START + 0x00000414)

// #define INTTAUB1I14_ENABLE              (IRQ_TABLE_START + 0x00000418)

// #define INTTAUB1I15_ENABLE              (IRQ_TABLE_START + 0x0000041C)

// #define INTRCAN4ERR_ENABLE              (IRQ_TABLE_START + 0x00000420)

// #define INTRCAN4REC_ENABLE              (IRQ_TABLE_START + 0x00000424)

// #define INTRCAN4TRX_ENABLE              (IRQ_TABLE_START + 0x00000428)

// #define INTRLIN26_ENABLE                (IRQ_TABLE_START + 0x0000042C)

// #define INTRLIN27_ENABLE                (IRQ_TABLE_START + 0x00000430)

// #define INTPWGA64_ENABLE                (IRQ_TABLE_START + 0x00000434)

// #define INTPWGA65_ENABLE                (IRQ_TABLE_START + 0x00000438)

// #define INTPWGA66_ENABLE                (IRQ_TABLE_START + 0x0000043C)

// #define INTPWGA67_ENABLE                (IRQ_TABLE_START + 0x00000440)

// #define INTPWGA68_ENABLE                (IRQ_TABLE_START + 0x00000444)

// #define INTPWGA69_ENABLE                (IRQ_TABLE_START + 0x00000448)

// #define INTPWGA70_ENABLE                (IRQ_TABLE_START + 0x0000044C)

// #define INTPWGA71_ENABLE                (IRQ_TABLE_START + 0x00000450)

// #define INTRLIN28_ENABLE                (IRQ_TABLE_START + 0x00000454)

// #define INTRLIN29_ENABLE                (IRQ_TABLE_START + 0x00000458)

// #define INTRCAN5ERR_ENABLE              (IRQ_TABLE_START + 0x0000045C)

// #define INTRCAN5REC_ENABLE              (IRQ_TABLE_START + 0x00000460)

// #define INTRCAN5TRX_ENABLE              (IRQ_TABLE_START + 0x00000464)



#endif /* __R7F701035xAFP_IRQ_H */
