/*
 MB96670 Series I/O register definition file V01L04
 ALL RIGHTS RESERVED, COPYRIGHT (C) FUJITSU SEMICONDUCTOR LIMITED 2010
 LICENSED MATERIAL - PROGRAM PROPERTY OF FUJITSU SEMICONDUCTOR LIMITED
*/

#define __IO_DEFINE
#include "_ffmc16.h"
